# This file is part of DmpBbo, a set of libraries and programs for the
# black-box optimization of dynamical movement primitives.
# Copyright (C) 2018 Freek Stulp
#
# DmpBbo is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# DmpBbo is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with DmpBbo.  If not, see <http://www.gnu.org/licenses/>.
""" Module for the TaskSolverDmp class. """

import copy

import numpy as np

from dmpbbo.bbo_of_dmps.TaskSolver import TaskSolver


class TaskSolverDmp(TaskSolver):
    """ TaskSolver that integrates a DMP.

    """

    def __init__(self, dmp, dt, integrate_dmp_beyond_tau_factor, return_dataframe=False):
        self._dmp = copy.deepcopy(dmp)
        self._integrate_time = dmp.tau * integrate_dmp_beyond_tau_factor
        self._n_time_steps = int(np.floor(self._integrate_time / dt)) + 1
        self._return_dataframe = return_dataframe

    def perform_rollout_dmp(self, dmp):
        """ Perform one rollout for a DMP.

        @param dmp: The DMP to integrate.
        @return: The trajectory generated by the DMP as a matrix.
        """
        ts = np.linspace(0.0, self._integrate_time, self._n_time_steps)
        xs, xds, forcing_terms, fa_outputs = dmp.analytical_solution(ts)
        traj = dmp.states_as_trajectory(ts, xs, xds)
        # traj.misc = forcing_terms

        if self._return_dataframe:
            return traj.as_dataframe()
        else:
            return traj.as_matrix()

    def perform_rollout(self, sample, **kwargs):
        """ Perform rollouts, that is, given a set of samples, determine all the variables that
        are relevant to evaluating the cost function.

        @param sample: The sample to perform the rollout for
        @return: The variables relevant to computing the cost.
        """
        self._dmp.set_param_vector(sample)
        return self.perform_rollout_dmp(self._dmp)
